# Training the Genre and Language LoRA Modules

Backbone: **`facebook/xglm-564M`** — a 564M-parameter decoder-only multilingual LM (standard
multi-head attention, no grouped-query attention)


**Module = LoRA adapter.** Each factor (genre 𝑔, language 𝑙) gets its own low-rank adapter on top
of the same frozen backbone, trained completely independently on the data prepared in
`01_data_extraction.ipynb`:

- **genre module** ← `data/genre_module_dgt_non_fi/` (OPUS DGT, all languages except Finnish)
- **language module** ← `data/language_module_books_fi/` (OPUS Books, Finnish only)

This notebook only trains thetwo modules; composing them and evaluating on the target domain is in a separate
notebook.

## 0. Setup

In [ ]:
import gc
import time
from pathlib import Path

import torch
from datasets import load_dataset
from peft import LoraConfig, get_peft_model
from transformers import (
    AutoModelForCausalLM,
    AutoTokenizer,
    DataCollatorForLanguageModeling,
    Trainer,
    TrainingArguments,
)

SEED = 42

DEVICE = "mps" if torch.backends.mps.is_available() else ("cuda" if torch.cuda.is_available() else "cpu")
print("device:", DEVICE)

MODEL_NAME = "facebook/xglm-564M"
DATA_DIR = Path("data")            # written by 01_data_extraction.ipynb
MODELS_DIR = Path("models")        # where each trained LoRA adapter gets saved
MODELS_DIR.mkdir(exist_ok=True)

/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

device: mps

## 1. Config

In [ ]:
MAX_LENGTH = 128            # covers ~90th percentile of sentence lengths in both corpora

# LoRA hyperparameters, identical for BOTH modules, since later are combines in
# weight space (ΔW_genre + ΔW_language); that only makes sense if both deltas live in a
# comparable low-rank subspace
LORA_R = 8
LORA_ALPHA = 16
LORA_DROPOUT = 0.05
TARGET_MODULES = ["q_proj", "k_proj", "v_proj", "out_proj"]  # xglm's attention proj names

LEARNING_RATE = 2e-4
BATCH_SIZE = 4
MAX_STEPS = 600           
                              
WARMUP_STEPS = 30
LOGGING_STEPS = 50
EVAL_STEPS = 150
EVAL_SUBSET_SIZE = 200

## 2. Tokenizer (shared, loaded once)

In [3]:
tokenizer = AutoTokenizer.from_pretrained(MODEL_NAME)
if tokenizer.pad_token is None:
    tokenizer.pad_token = tokenizer.eos_token  # XGLM has no dedicated pad token

def tokenize(example):
    return tokenizer(example["text"], truncation=True, max_length=MAX_LENGTH)

## 3. Helpers

In [ ]:
def load_tokenized_split(path, max_examples=None):
    ds = load_dataset("json", data_files=str(path), split="train")
    if max_examples is not None and len(ds) > max_examples:
        ds = ds.shuffle(seed=SEED).select(range(max_examples))
    return ds.map(tokenize, remove_columns=ds.column_names)


def fresh_lora_model():
    """A new frozen backbone + a freshly-initialized LoRA adapter, so every module is
    trained from scratch with zero state shared with any previously trained module."""
    base = AutoModelForCausalLM.from_pretrained(MODEL_NAME, torch_dtype=torch.bfloat16)
    lora_cfg = LoraConfig(
        r=LORA_R,
        lora_alpha=LORA_ALPHA,
        lora_dropout=LORA_DROPOUT,
        target_modules=TARGET_MODULES,
        task_type="CAUSAL_LM",
    )
    model = get_peft_model(base, lora_cfg)  # freezes the backbone, adds trainable LoRA A/B matrices
    model.to(DEVICE)
    return model


def free(*objs):
    """Cleanup between the two module-training runs."""
    for o in objs:
        del o
    gc.collect()
    if DEVICE == "mps":
        torch.mps.empty_cache()
    elif DEVICE == "cuda":
        torch.cuda.empty_cache()


def train_module(name, train_path, dev_path, output_dir):
    print(f"\n=== training {name} module ===")
    train_ds = load_tokenized_split(train_path)
    dev_ds = load_tokenized_split(dev_path, max_examples=EVAL_SUBSET_SIZE)
    print(f"train examples: {len(train_ds):,} | eval examples: {len(dev_ds):,}")

    model = fresh_lora_model()
    model.print_trainable_parameters()  # sanity check: should be a small fraction of all params

    # mlm=False -> causal LM collation: labels are a (shifted) copy of input_ids, pad positions masked
    collator = DataCollatorForLanguageModeling(tokenizer, mlm=False)

    args = TrainingArguments(
        output_dir=f"runs/{name}",
        per_device_train_batch_size=BATCH_SIZE,
        per_device_eval_batch_size=BATCH_SIZE,
        max_steps=MAX_STEPS,
        learning_rate=LEARNING_RATE,
        warmup_steps=WARMUP_STEPS,
        logging_steps=LOGGING_STEPS,
        eval_strategy="steps",
        eval_steps=EVAL_STEPS,
        save_strategy="no",   # adapter is saved manually below; no need for HF checkpoints
        report_to="none",
        seed=SEED,
    )

    trainer = Trainer(
        model=model,
        args=args,
        train_dataset=train_ds,
        eval_dataset=dev_ds,
        data_collator=collator,
    )

    # LoRA's B matrix is zero-initialized, so the model at step 0 is numerically identical
    # to the plain backbone — this eval *is* the pre-adaptation baseline, no extra model load needed.
    baseline = trainer.evaluate()
    t0 = time.time()
    trainer.train()
    elapsed = time.time() - t0
    final = trainer.evaluate()

    Path(output_dir).mkdir(parents=True, exist_ok=True)
    model.save_pretrained(output_dir)   # only the small LoRA adapter is written, not the backbone
    tokenizer.save_pretrained(output_dir)
    print(f"saved adapter to {output_dir} ({elapsed/60:.1f} min)")

    result = {
        "module": name,
        "baseline_loss": baseline["eval_loss"],
        "final_loss": final["eval_loss"],
        "minutes": elapsed / 60,
    }

    free(model, trainer)
    return result

## 4. Train the genre module

`g` = legal/administrative register, learned from OPUS DGT in every available language **except**
Finnish (𝐿∖𝑙).

In [ ]:
# g = legal/administrative register, learned from every DGT language EXCEPT Finnish (L∖l)
genre_result = train_module(
    name="genre",
    train_path=DATA_DIR / "genre_module_dgt_non_fi" / "train.jsonl",
    dev_path=DATA_DIR / "genre_module_dgt_non_fi" / "dev.jsonl",
    output_dir=MODELS_DIR / "genre_module_dgt",
)
genre_result

=== training genre module ===

Map:   0%|          | 0/445500 [00:00<?, ? examples/s]

Map:   0%|          | 759/445500 [00:00<00:58, 7552.30 examples/s]

Map:   0%|          | 1939/445500 [00:00<00:57, 7759.22 examples/s]

Map:   1%|          | 2810/445500 [00:00<00:54, 8124.70 examples/s]

Map:   1%|          | 3691/445500 [00:00<00:52, 8368.98 examples/s]

Map:   1%|          | 4550/445500 [00:00<00:52, 8441.05 examples/s]

Map:   1%|          | 5398/445500 [00:00<00:52, 8449.55 examples/s]

Map:   1%|▏         | 6251/445500 [00:00<00:51, 8467.26 examples/s]

Map:   2%|▏         | 7512/445500 [00:00<00:51, 8439.19 examples/s]

Map:   2%|▏         | 8358/445500 [00:01<00:51, 8444.56 examples/s]

Map:   2%|▏         | 9206/445500 [00:01<00:51, 8448.65 examples/s]

Map:   2%|▏         | 10054/445500 [00:01<00:51, 8451.16 examples/s]

Map:   2%|▏         | 10900/445500 [00:01<00:51, 8452.01 examples/s]

Map:   3%|▎         | 11750/445500 [00:01<00:51, 8465.42 examples/s]

Map:   3%|▎         | 12640/445500 [00:01<00:50, 8591.22 examples/s]

Map:   3%|▎         | 13505/445500 [00:01<00:50, 8607.12 examples/s]

Map:   3%|▎         | 14795/445500 [00:01<00:50, 8596.40 examples/s]

Map:   4%|▎         | 15662/445500 [00:01<00:49, 8608.51 examples/s]

Map:   4%|▍         | 16913/445500 [00:02<00:50, 8505.87 examples/s]

Map:   4%|▍         | 17808/445500 [00:02<00:49, 8609.56 examples/s]

Map:   4%|▍         | 19064/445500 [00:02<00:50, 8520.99 examples/s]

Map:   4%|▍         | 19931/445500 [00:02<00:49, 8552.57 examples/s]

Map:   5%|▍         | 21216/445500 [00:02<00:49, 8555.44 examples/s]

Map:   5%|▍         | 22084/445500 [00:02<00:49, 8583.17 examples/s]

Map:   5%|▌         | 22958/445500 [00:02<00:49, 8621.85 examples/s]

Map:   5%|▌         | 24236/445500 [00:02<00:49, 8579.26 examples/s]

Map:   6%|▌         | 25101/445500 [00:02<00:48, 8593.53 examples/s]

Map:   6%|▌         | 25970/445500 [00:03<00:48, 8608.97 examples/s]

Map:   6%|▌         | 27229/445500 [00:03<00:49, 8528.48 examples/s]

Map:   6%|▋         | 28502/445500 [00:03<00:49, 8508.57 examples/s]

Map:   7%|▋         | 29797/445500 [00:03<00:48, 8544.42 examples/s]

Map:   7%|▋         | 31012/445500 [00:03<00:49, 8397.32 examples/s]

Map:   7%|▋         | 31897/445500 [00:03<00:48, 8501.69 examples/s]

Map:   7%|▋         | 33163/445500 [00:03<00:48, 8475.84 examples/s]

Map:   8%|▊         | 34020/445500 [00:04<00:48, 8497.25 examples/s]

Map:   8%|▊         | 34889/445500 [00:04<00:48, 8543.93 examples/s]

Map:   8%|▊         | 35753/445500 [00:04<00:47, 8568.60 examples/s]

Map:   8%|▊         | 36626/445500 [00:04<00:47, 8609.85 examples/s]

Map:   8%|▊         | 37495/445500 [00:04<00:47, 8631.58 examples/s]

Map:   9%|▊         | 38755/445500 [00:04<00:47, 8540.48 examples/s]

Map:   9%|▉         | 40020/445500 [00:04<00:47, 8501.73 examples/s]

Map:   9%|▉         | 40897/445500 [00:04<00:47, 8567.49 examples/s]

Map:   9%|▉         | 42148/445500 [00:04<00:47, 8486.49 examples/s]

Map:  10%|▉         | 43022/445500 [00:05<00:47, 8547.82 examples/s]

Map:  10%|▉         | 43911/445500 [00:05<00:46, 8637.09 examples/s]

Map:  10%|█         | 45190/445500 [00:05<00:46, 8595.35 examples/s]

Map:  10%|█         | 46468/445500 [00:05<00:46, 8566.69 examples/s]

Map:  11%|█         | 47780/445500 [00:05<00:46, 8625.12 examples/s]

Map:  11%|█         | 49012/445500 [00:05<00:46, 8492.10 examples/s]

Map:  11%|█         | 49904/445500 [00:05<00:46, 8589.63 examples/s]

Map:  11%|█▏        | 50777/445500 [00:05<00:45, 8623.05 examples/s]

Map:  12%|█▏        | 51651/445500 [00:06<00:45, 8652.98 examples/s]

Map:  12%|█▏        | 52923/445500 [00:06<00:45, 8590.02 examples/s]

Map:  12%|█▏        | 54188/445500 [00:06<00:45, 8533.85 examples/s]

Map:  12%|█▏        | 55474/445500 [00:06<00:45, 8545.69 examples/s]

Map:  13%|█▎        | 56770/445500 [00:06<00:45, 8573.65 examples/s]

Map:  13%|█▎        | 58000/445500 [00:06<00:45, 8445.01 examples/s]

Map:  13%|█▎        | 58858/445500 [00:06<00:45, 8473.10 examples/s]

Map:  13%|█▎        | 60116/445500 [00:07<00:45, 8441.25 examples/s]

Map:  14%|█▍        | 61332/445500 [00:07<00:46, 8327.68 examples/s]

Map:  14%|█▍        | 62589/445500 [00:07<00:45, 8336.52 examples/s]

Map:  14%|█▍        | 63447/445500 [00:07<00:45, 8392.16 examples/s]

Map:  14%|█▍        | 64305/445500 [00:07<00:45, 8434.77 examples/s]

Map:  15%|█▍        | 65576/445500 [00:07<00:44, 8444.67 examples/s]

Map:  15%|█▍        | 66426/445500 [00:07<00:44, 8432.46 examples/s]

Map:  15%|█▌        | 67689/445500 [00:07<00:44, 8424.89 examples/s]

Map:  15%|█▌        | 68972/445500 [00:08<00:44, 8465.27 examples/s]

Map:  16%|█▌        | 70211/445500 [00:08<00:44, 8396.37 examples/s]

Map:  16%|█▌        | 71083/445500 [00:08<00:44, 8470.29 examples/s]

Map:  16%|█▌        | 71979/445500 [00:08<00:43, 8582.29 examples/s]

Map:  16%|█▋        | 73226/445500 [00:08<00:43, 8480.34 examples/s]

Map:  17%|█▋        | 74501/445500 [00:08<00:43, 8480.54 examples/s]

Map:  17%|█▋        | 75353/445500 [00:08<00:43, 8487.54 examples/s]

Map:  17%|█▋        | 76208/445500 [00:08<00:43, 8496.49 examples/s]

Map:  17%|█▋        | 77457/445500 [00:09<00:43, 8434.04 examples/s]

Map:  18%|█▊        | 78310/445500 [00:09<00:43, 8455.68 examples/s]

Map:  18%|█▊        | 79564/445500 [00:09<00:43, 8416.86 examples/s]

Map:  18%|█▊        | 80434/445500 [00:09<00:43, 8455.24 examples/s]

Map:  18%|█▊        | 81706/445500 [00:09<00:43, 8457.91 examples/s]

Map:  19%|█▊        | 82985/445500 [00:09<00:42, 8479.14 examples/s]

Map:  19%|█▉        | 84193/445500 [00:09<00:43, 8335.89 examples/s]

Map:  19%|█▉        | 85045/445500 [00:10<00:43, 8375.94 examples/s]

Map:  19%|█▉        | 85918/445500 [00:10<00:42, 8459.56 examples/s]

Map:  20%|█▉        | 87180/445500 [00:10<00:42, 8440.66 examples/s]

Map:  20%|█▉        | 88027/445500 [00:10<00:42, 8446.67 examples/s]

Map:  20%|█▉        | 88889/445500 [00:10<00:41, 8491.56 examples/s]

Map:  20%|██        | 89751/445500 [00:10<00:41, 8521.57 examples/s]

Map:  20%|██        | 90609/445500 [00:10<00:41, 8535.30 examples/s]

Map:  21%|██        | 91897/445500 [00:10<00:41, 8550.30 examples/s]

Map:  21%|██        | 92777/445500 [00:10<00:40, 8610.60 examples/s]

Map:  21%|██        | 94032/445500 [00:11<00:41, 8520.36 examples/s]

Map:  21%|██▏       | 94926/445500 [00:11<00:40, 8622.21 examples/s]

Map:  22%|██▏       | 96215/445500 [00:11<00:40, 8606.66 examples/s]

Map:  22%|██▏       | 97483/445500 [00:11<00:40, 8550.42 examples/s]

Map:  22%|██▏       | 98740/445500 [00:11<00:40, 8492.52 examples/s]

Map:  22%|██▏       | 100000/445500 [00:11<00:41, 8420.26 examples/s]

Map:  23%|██▎       | 101211/445500 [00:11<00:41, 8306.73 examples/s]

Map:  23%|██▎       | 102399/445500 [00:12<00:41, 8180.55 examples/s]

Map:  23%|██▎       | 103225/445500 [00:12<00:41, 8193.78 examples/s]

Map:  23%|██▎       | 104088/445500 [00:12<00:41, 8295.71 examples/s]

Map:  24%|██▎       | 104956/445500 [00:12<00:40, 8392.01 examples/s]

Map:  24%|██▍       | 106208/445500 [00:12<00:40, 8372.44 examples/s]

Map:  24%|██▍       | 107090/445500 [00:12<00:39, 8483.87 examples/s]

Map:  24%|██▍       | 107996/445500 [00:12<00:39, 8632.02 examples/s]

Map:  25%|██▍       | 109252/445500 [00:12<00:39, 8532.20 examples/s]

Map:  25%|██▍       | 110521/445500 [00:13<00:39, 8505.71 examples/s]

Map:  25%|██▌       | 111754/445500 [00:13<00:39, 8409.16 examples/s]

Map:  25%|██▌       | 112612/445500 [00:13<00:39, 8448.13 examples/s]

Map:  26%|██▌       | 113856/445500 [00:13<00:39, 8390.47 examples/s]

Map:  26%|██▌       | 114709/445500 [00:13<00:39, 8422.92 examples/s]

Map:  26%|██▌       | 115973/445500 [00:13<00:39, 8422.50 examples/s]

Map:  26%|██▋       | 117209/445500 [00:13<00:39, 8358.36 examples/s]

Map:  26%|██▋       | 118049/445500 [00:13<00:39, 8366.22 examples/s]

Map:  27%|██▋       | 118905/445500 [00:14<00:38, 8410.16 examples/s]

Map:  27%|██▋       | 120119/445500 [00:14<00:39, 8292.12 examples/s]

Map:  27%|██▋       | 120980/445500 [00:14<00:38, 8371.26 examples/s]

Map:  27%|██▋       | 121829/445500 [00:14<00:38, 8399.08 examples/s]

Map:  28%|██▊       | 123054/445500 [00:14<00:38, 8313.16 examples/s]

Map:  28%|██▊       | 123896/445500 [00:14<00:38, 8331.87 examples/s]

Map:  28%|██▊       | 124741/445500 [00:14<00:38, 8358.06 examples/s]

Map:  28%|██▊       | 125588/445500 [00:14<00:38, 8386.77 examples/s]

Map:  28%|██▊       | 126839/445500 [00:14<00:38, 8360.80 examples/s]

Map:  29%|██▊       | 127696/445500 [00:15<00:37, 8412.39 examples/s]

Map:  29%|██▉       | 128554/445500 [00:15<00:37, 8456.70 examples/s]

Map:  29%|██▉       | 129841/445500 [00:15<00:37, 8497.24 examples/s]

Map:  29%|██▉       | 131065/445500 [00:15<00:37, 8352.37 examples/s]

Map:  30%|██▉       | 131926/445500 [00:15<00:37, 8414.91 examples/s]

Map:  30%|██▉       | 133184/445500 [00:15<00:37, 8403.08 examples/s]

Map:  30%|███       | 134418/445500 [00:15<00:37, 8339.10 examples/s]

Map:  30%|███       | 135637/445500 [00:16<00:37, 8207.80 examples/s]

Map:  31%|███       | 136879/445500 [00:16<00:37, 8226.92 examples/s]

Map:  31%|███       | 138104/445500 [00:16<00:37, 8196.49 examples/s]

Map:  31%|███       | 138966/445500 [00:16<00:36, 8290.28 examples/s]

Map:  31%|███▏      | 140208/445500 [00:16<00:36, 8281.31 examples/s]

Map:  32%|███▏      | 141056/445500 [00:16<00:36, 8325.21 examples/s]

Map:  32%|███▏      | 142235/445500 [00:16<00:37, 8165.07 examples/s]

Map:  32%|███▏      | 143074/445500 [00:16<00:36, 8216.76 examples/s]

Map:  32%|███▏      | 143921/445500 [00:17<00:36, 8279.60 examples/s]

Map:  33%|███▎      | 145162/445500 [00:17<00:36, 8275.76 examples/s]

Map:  33%|███▎      | 146011/445500 [00:17<00:35, 8328.67 examples/s]

Map:  33%|███▎      | 146918/445500 [00:17<00:35, 8519.76 examples/s]

Map:  33%|███▎      | 148144/445500 [00:17<00:35, 8389.91 examples/s]

Map:  34%|███▎      | 149383/445500 [00:17<00:35, 8341.34 examples/s]

Map:  34%|███▎      | 150250/445500 [00:17<00:35, 8418.82 examples/s]

Map:  34%|███▍      | 151108/445500 [00:17<00:34, 8457.48 examples/s]

Map:  34%|███▍      | 151991/445500 [00:17<00:34, 8554.91 examples/s]

Map:  34%|███▍      | 153230/445500 [00:18<00:34, 8443.87 examples/s]

Map:  35%|███▍      | 154462/445500 [00:18<00:34, 8362.03 examples/s]

Map:  35%|███▍      | 155316/445500 [00:18<00:34, 8402.03 examples/s]

Map:  35%|███▌      | 156585/445500 [00:18<00:34, 8418.51 examples/s]

Map:  35%|███▌      | 157837/445500 [00:18<00:34, 8359.81 examples/s]

Map:  36%|███▌      | 158693/445500 [00:18<00:34, 8406.12 examples/s]

Map:  36%|███▌      | 159940/445500 [00:18<00:34, 8370.34 examples/s]

Map:  36%|███▌      | 161176/445500 [00:19<00:34, 8323.53 examples/s]

Map:  36%|███▋      | 162046/445500 [00:19<00:33, 8409.74 examples/s]

Map:  37%|███▋      | 162897/445500 [00:19<00:33, 8431.95 examples/s]

Map:  37%|███▋      | 164136/445500 [00:19<00:33, 8369.10 examples/s]

Map:  37%|███▋      | 165000/445500 [00:19<00:33, 8432.29 examples/s]

Map:  37%|███▋      | 166255/445500 [00:19<00:33, 8405.25 examples/s]

Map:  38%|███▊      | 167504/445500 [00:19<00:33, 8375.48 examples/s]

Map:  38%|███▊      | 168356/445500 [00:19<00:32, 8408.02 examples/s]

Map:  38%|███▊      | 169598/445500 [00:20<00:32, 8362.51 examples/s]

Map:  38%|███▊      | 170874/445500 [00:20<00:32, 8405.41 examples/s]

Map:  39%|███▊      | 172121/445500 [00:20<00:32, 8373.96 examples/s]

Map:  39%|███▉      | 172985/445500 [00:20<00:32, 8433.77 examples/s]

Map:  39%|███▉      | 174230/445500 [00:20<00:32, 8385.18 examples/s]

Map:  39%|███▉      | 175466/445500 [00:20<00:32, 8331.77 examples/s]

Map:  40%|███▉      | 176328/445500 [00:20<00:32, 8390.31 examples/s]

Map:  40%|███▉      | 177170/445500 [00:20<00:31, 8395.59 examples/s]

Map:  40%|███▉      | 178023/445500 [00:21<00:31, 8426.36 examples/s]

Map:  40%|████      | 179254/445500 [00:21<00:31, 8341.54 examples/s]

Map:  40%|████      | 180118/445500 [00:21<00:31, 8414.45 examples/s]

Map:  41%|████      | 181358/445500 [00:21<00:31, 8361.19 examples/s]

Map:  41%|████      | 182601/445500 [00:21<00:31, 8332.40 examples/s]

Map:  41%|████▏     | 183843/445500 [00:21<00:31, 8313.39 examples/s]

Map:  41%|████▏     | 184704/445500 [00:21<00:31, 8382.22 examples/s]

Map:  42%|████▏     | 185928/445500 [00:22<00:31, 8299.06 examples/s]

Map:  42%|████▏     | 187124/445500 [00:22<00:31, 8190.89 examples/s]

Map:  42%|████▏     | 187955/445500 [00:22<00:31, 8215.07 examples/s]

Map:  42%|████▏     | 189176/445500 [00:22<00:31, 8183.20 examples/s]

Map:  43%|████▎     | 190019/445500 [00:22<00:31, 8240.52 examples/s]

Map:  43%|████▎     | 190885/445500 [00:22<00:30, 8346.88 examples/s]

Map:  43%|████▎     | 192085/445500 [00:22<00:30, 8216.88 examples/s]

Map:  43%|████▎     | 192969/445500 [00:22<00:30, 8373.78 examples/s]

Map:  44%|████▎     | 194190/445500 [00:23<00:30, 8285.48 examples/s]

Map:  44%|████▍     | 195441/445500 [00:23<00:30, 8299.86 examples/s]

Map:  44%|████▍     | 196696/445500 [00:23<00:29, 8319.37 examples/s]

Map:  44%|████▍     | 197544/445500 [00:23<00:29, 8356.38 examples/s]

Map:  45%|████▍     | 198408/445500 [00:23<00:29, 8425.71 examples/s]

Map:  45%|████▍     | 199683/445500 [00:23<00:29, 8448.99 examples/s]

Map:  45%|████▌     | 200543/445500 [00:23<00:28, 8479.41 examples/s]

Map:  45%|████▌     | 201845/445500 [00:23<00:28, 8541.81 examples/s]

Map:  46%|████▌     | 203041/445500 [00:24<00:29, 8342.34 examples/s]

Map:  46%|████▌     | 204254/445500 [00:24<00:29, 8254.82 examples/s]

Map:  46%|████▌     | 205109/445500 [00:24<00:28, 8323.11 examples/s]

Map:  46%|████▌     | 205974/445500 [00:24<00:28, 8401.68 examples/s]

Map:  46%|████▋     | 206846/445500 [00:24<00:28, 8479.08 examples/s]

Map:  47%|████▋     | 208089/445500 [00:24<00:28, 8402.19 examples/s]

Map:  47%|████▋     | 208937/445500 [00:24<00:28, 8418.34 examples/s]

Map:  47%|████▋     | 210154/445500 [00:24<00:28, 8306.98 examples/s]

Map:  47%|████▋     | 211010/445500 [00:25<00:28, 8369.55 examples/s]

Map:  48%|████▊     | 211909/445500 [00:25<00:27, 8530.55 examples/s]

Map:  48%|████▊     | 213149/445500 [00:25<00:27, 8428.31 examples/s]

Map:  48%|████▊     | 213998/445500 [00:25<00:27, 8439.78 examples/s]

Map:  48%|████▊     | 215225/445500 [00:25<00:27, 8343.86 examples/s]

Map:  49%|████▊     | 216505/445500 [00:25<00:27, 8402.91 examples/s]

Map:  49%|████▉     | 217760/445500 [00:25<00:27, 8386.60 examples/s]

Map:  49%|████▉     | 218636/445500 [00:25<00:26, 8469.53 examples/s]

Map:  49%|████▉     | 219495/445500 [00:26<00:26, 8497.02 examples/s]

Map:  50%|████▉     | 220748/445500 [00:26<00:26, 8442.72 examples/s]

Map:  50%|████▉     | 221610/445500 [00:26<00:26, 8485.20 examples/s]

Map:  50%|████▉     | 222478/445500 [00:26<00:26, 8535.69 examples/s]

Map:  50%|█████     | 223769/445500 [00:26<00:25, 8556.29 examples/s]

Map:  51%|█████     | 225005/445500 [00:26<00:26, 8440.13 examples/s]

Map:  51%|█████     | 225853/445500 [00:26<00:26, 8447.50 examples/s]

Map:  51%|█████     | 227076/445500 [00:26<00:26, 8344.25 examples/s]

Map:  51%|█████     | 227927/445500 [00:27<00:25, 8382.71 examples/s]

Map:  51%|█████▏    | 229182/445500 [00:27<00:25, 8372.92 examples/s]

Map:  52%|█████▏    | 230025/445500 [00:27<00:25, 8383.75 examples/s]

Map:  52%|█████▏    | 231252/445500 [00:27<00:25, 8304.51 examples/s]

Map:  52%|█████▏    | 232097/445500 [00:27<00:25, 8339.87 examples/s]

Map:  52%|█████▏    | 232946/445500 [00:27<00:25, 8374.00 examples/s]

Map:  52%|█████▏    | 233793/445500 [00:27<00:25, 8398.27 examples/s]

Map:  53%|█████▎    | 235040/445500 [00:27<00:25, 8363.39 examples/s]

Map:  53%|█████▎    | 235913/445500 [00:28<00:24, 8457.99 examples/s]

Map:  53%|█████▎    | 237150/445500 [00:28<00:24, 8378.43 examples/s]

Map:  54%|█████▎    | 238378/445500 [00:28<00:24, 8308.96 examples/s]

Map:  54%|█████▎    | 239212/445500 [00:28<00:24, 8312.53 examples/s]

Map:  54%|█████▍    | 240063/445500 [00:28<00:24, 8352.31 examples/s]

Map:  54%|█████▍    | 241296/445500 [00:28<00:24, 8301.39 examples/s]

Map:  54%|█████▍    | 242554/445500 [00:28<00:24, 8313.62 examples/s]

Map:  55%|█████▍    | 243424/445500 [00:28<00:24, 8404.45 examples/s]

Map:  55%|█████▍    | 244680/445500 [00:29<00:23, 8392.42 examples/s]

Map:  55%|█████▌    | 245526/445500 [00:29<00:23, 8406.87 examples/s]

Map:  55%|█████▌    | 246805/445500 [00:29<00:23, 8444.46 examples/s]

Map:  56%|█████▌    | 248040/445500 [00:29<00:23, 8370.97 examples/s]

Map:  56%|█████▌    | 248894/445500 [00:29<00:23, 8411.23 examples/s]

Map:  56%|█████▌    | 250134/445500 [00:29<00:23, 8358.98 examples/s]

Map:  56%|█████▋    | 251000/445500 [00:29<00:23, 8388.83 examples/s]

Map:  57%|█████▋    | 251869/445500 [00:29<00:22, 8460.73 examples/s]

Map:  57%|█████▋    | 252719/445500 [00:30<00:22, 8467.67 examples/s]

Map:  57%|█████▋    | 253978/445500 [00:30<00:22, 8433.72 examples/s]

Map:  57%|█████▋    | 254825/445500 [00:30<00:22, 8438.20 examples/s]

Map:  57%|█████▋    | 256052/445500 [00:30<00:22, 8345.43 examples/s]

Map:  58%|█████▊    | 256898/445500 [00:30<00:22, 8372.12 examples/s]

Map:  58%|█████▊    | 257753/445500 [00:30<00:22, 8417.31 examples/s]

Map:  58%|█████▊    | 259000/445500 [00:30<00:22, 8333.83 examples/s]

Map:  58%|█████▊    | 259880/445500 [00:30<00:21, 8450.27 examples/s]

Map:  59%|█████▊    | 261114/445500 [00:31<00:22, 8368.49 examples/s]

Map:  59%|█████▉    | 262000/445500 [00:31<00:21, 8450.37 examples/s]

Map:  59%|█████▉    | 262891/445500 [00:31<00:21, 8567.32 examples/s]

Map:  59%|█████▉    | 264110/445500 [00:31<00:21, 8401.61 examples/s]

Map:  60%|█████▉    | 265368/445500 [00:31<00:21, 8390.82 examples/s]

Map:  60%|█████▉    | 266623/445500 [00:31<00:21, 8379.20 examples/s]

Map:  60%|██████    | 267860/445500 [00:31<00:21, 8332.57 examples/s]

Map:  60%|██████    | 269032/445500 [00:31<00:21, 8161.21 examples/s]

Map:  61%|██████    | 269879/445500 [00:32<00:21, 8230.72 examples/s]

Map:  61%|██████    | 271079/445500 [00:32<00:21, 8151.16 examples/s]

Map:  61%|██████    | 271924/445500 [00:32<00:21, 8221.11 examples/s]

Map:  61%|██████    | 272763/445500 [00:32<00:20, 8261.98 examples/s]

Map:  61%|██████▏   | 273607/445500 [00:32<00:20, 8306.69 examples/s]

Map:  62%|██████▏   | 274473/445500 [00:32<00:20, 8400.03 examples/s]

Map:  62%|██████▏   | 275735/445500 [00:32<00:20, 8400.98 examples/s]

Map:  62%|██████▏   | 276992/445500 [00:32<00:20, 8388.31 examples/s]

Map:  62%|██████▏   | 277836/445500 [00:33<00:19, 8396.46 examples/s]

Map:  63%|██████▎   | 279045/445500 [00:33<00:20, 8277.30 examples/s]

Map:  63%|██████▎   | 279895/445500 [00:33<00:19, 8329.07 examples/s]

Map:  63%|██████▎   | 280734/445500 [00:33<00:19, 8335.26 examples/s]

Map:  63%|██████▎   | 281580/445500 [00:33<00:19, 8368.26 examples/s]

Map:  63%|██████▎   | 282803/445500 [00:33<00:19, 8283.76 examples/s]

Map:  64%|██████▍   | 284032/445500 [00:33<00:19, 8246.29 examples/s]

Map:  64%|██████▍   | 284878/445500 [00:33<00:19, 8295.78 examples/s]

Map:  64%|██████▍   | 285712/445500 [00:33<00:19, 8304.66 examples/s]

Map:  64%|██████▍   | 286973/445500 [00:34<00:19, 8336.71 examples/s]

Map:  65%|██████▍   | 287813/445500 [00:34<00:18, 8350.36 examples/s]

Map:  65%|██████▍   | 288649/445500 [00:34<00:18, 8350.53 examples/s]

Map:  65%|██████▌   | 289880/445500 [00:34<00:18, 8289.98 examples/s]

Map:  65%|██████▌   | 291058/445500 [00:34<00:18, 8138.40 examples/s]

Map:  66%|██████▌   | 291879/445500 [00:34<00:18, 8155.81 examples/s]

Map:  66%|██████▌   | 293093/445500 [00:34<00:18, 8128.43 examples/s]

Map:  66%|██████▌   | 293927/445500 [00:34<00:18, 8180.02 examples/s]

Map:  66%|██████▌   | 294755/445500 [00:35<00:18, 8203.24 examples/s]

Map:  66%|██████▋   | 295613/445500 [00:35<00:18, 8301.97 examples/s]

Map:  67%|██████▋   | 296874/445500 [00:35<00:17, 8334.14 examples/s]

Map:  67%|██████▋   | 297711/445500 [00:35<00:17, 8332.76 examples/s]

Map:  67%|██████▋   | 298974/445500 [00:35<00:17, 8361.45 examples/s]

Map:  67%|██████▋   | 299840/445500 [00:35<00:17, 8434.68 examples/s]

Map:  67%|██████▋   | 300710/445500 [00:35<00:17, 8500.45 examples/s]

Map:  68%|██████▊   | 301993/445500 [00:35<00:16, 8504.72 examples/s]

Map:  68%|██████▊   | 303218/445500 [00:36<00:16, 8386.60 examples/s]

Map:  68%|██████▊   | 304060/445500 [00:36<00:16, 8389.11 examples/s]

Map:  68%|██████▊   | 304951/445500 [00:36<00:16, 8520.56 examples/s]

Map:  69%|██████▊   | 305807/445500 [00:36<00:16, 8523.87 examples/s]

Map:  69%|██████▉   | 307050/445500 [00:36<00:16, 8432.32 examples/s]

Map:  69%|██████▉   | 308235/445500 [00:36<00:16, 8245.67 examples/s]

Map:  69%|██████▉   | 309081/445500 [00:36<00:16, 8296.21 examples/s]

Map:  70%|██████▉   | 309923/445500 [00:36<00:16, 8326.51 examples/s]

Map:  70%|██████▉   | 311162/445500 [00:37<00:16, 8301.22 examples/s]

Map:  70%|███████   | 312000/445500 [00:37<00:16, 8304.89 examples/s]

Map:  70%|███████   | 312849/445500 [00:37<00:15, 8350.96 examples/s]

Map:  70%|███████   | 313691/445500 [00:37<00:15, 8358.55 examples/s]

Map:  71%|███████   | 314562/445500 [00:37<00:15, 8455.23 examples/s]

Map:  71%|███████   | 315803/445500 [00:37<00:15, 8384.83 examples/s]

Map:  71%|███████   | 317047/445500 [00:37<00:15, 8337.00 examples/s]

Map:  71%|███████▏  | 317899/445500 [00:37<00:15, 8380.01 examples/s]

Map:  72%|███████▏  | 319110/445500 [00:37<00:15, 8272.21 examples/s]

Map:  72%|███████▏  | 319980/445500 [00:38<00:14, 8377.36 examples/s]

Map:  72%|███████▏  | 320846/445500 [00:38<00:14, 8450.20 examples/s]

Map:  72%|███████▏  | 321709/445500 [00:38<00:14, 8495.88 examples/s]

Map:  73%|███████▎  | 322991/445500 [00:38<00:14, 8505.53 examples/s]

Map:  73%|███████▎  | 324177/445500 [00:38<00:14, 8294.12 examples/s]

Map:  73%|███████▎  | 325018/445500 [00:38<00:14, 8319.20 examples/s]

Map:  73%|███████▎  | 325918/445500 [00:38<00:14, 8492.49 examples/s]

Map:  73%|███████▎  | 327137/445500 [00:38<00:14, 8355.65 examples/s]

Map:  74%|███████▎  | 327986/445500 [00:39<00:14, 8380.81 examples/s]

Map:  74%|███████▍  | 329214/445500 [00:39<00:13, 8309.22 examples/s]

Map:  74%|███████▍  | 330084/445500 [00:39<00:13, 8405.94 examples/s]

Map:  74%|███████▍  | 330961/445500 [00:39<00:13, 8500.79 examples/s]

Map:  75%|███████▍  | 332217/445500 [00:39<00:13, 8448.44 examples/s]

Map:  75%|███████▍  | 333481/445500 [00:39<00:13, 8437.01 examples/s]

Map:  75%|███████▌  | 334750/445500 [00:39<00:13, 8437.15 examples/s]

Map:  75%|███████▌  | 335602/445500 [00:39<00:13, 8451.48 examples/s]

Map:  76%|███████▌  | 336853/445500 [00:40<00:12, 8409.38 examples/s]

Map:  76%|███████▌  | 338065/445500 [00:40<00:12, 8297.43 examples/s]

Map:  76%|███████▌  | 338936/445500 [00:40<00:12, 8391.33 examples/s]

Map:  76%|███████▋  | 340175/445500 [00:40<00:12, 8345.51 examples/s]

Map:  77%|███████▋  | 341434/445500 [00:40<00:12, 8355.42 examples/s]

Map:  77%|███████▋  | 342682/445500 [00:40<00:12, 8341.17 examples/s]

Map:  77%|███████▋  | 343947/445500 [00:40<00:12, 8365.96 examples/s]

Map:  77%|███████▋  | 345190/445500 [00:41<00:12, 8337.94 examples/s]

Map:  78%|███████▊  | 346055/445500 [00:41<00:11, 8407.82 examples/s]

Map:  78%|███████▊  | 346943/445500 [00:41<00:11, 8520.43 examples/s]

Map:  78%|███████▊  | 348214/445500 [00:41<00:11, 8499.78 examples/s]

Map:  78%|███████▊  | 349079/445500 [00:41<00:11, 8532.14 examples/s]

Map:  79%|███████▊  | 350304/445500 [00:41<00:11, 8400.28 examples/s]

Map:  79%|███████▉  | 351513/445500 [00:41<00:11, 8285.48 examples/s]

Map:  79%|███████▉  | 352767/445500 [00:41<00:11, 8306.42 examples/s]

Map:  79%|███████▉  | 354000/445500 [00:42<00:11, 8268.26 examples/s]

Map:  80%|███████▉  | 354875/445500 [00:42<00:10, 8377.57 examples/s]

Map:  80%|███████▉  | 355736/445500 [00:42<00:10, 8433.10 examples/s]

Map:  80%|████████  | 356593/445500 [00:42<00:10, 8465.23 examples/s]

Map:  80%|████████  | 357461/445500 [00:42<00:10, 8520.86 examples/s]

Map:  81%|████████  | 358709/445500 [00:42<00:10, 8442.74 examples/s]

Map:  81%|████████  | 359991/445500 [00:42<00:10, 8476.86 examples/s]

Map:  81%|████████  | 361223/445500 [00:42<00:10, 8387.78 examples/s]

Map:  81%|████████▏ | 362094/445500 [00:43<00:09, 8461.76 examples/s]

Map:  81%|████████▏ | 362948/445500 [00:43<00:09, 8481.01 examples/s]

Map:  82%|████████▏ | 364210/445500 [00:43<00:09, 8454.32 examples/s]

Map:  82%|████████▏ | 365473/445500 [00:43<00:09, 8440.10 examples/s]

Map:  82%|████████▏ | 366336/445500 [00:43<00:09, 8484.65 examples/s]

Map:  83%|████████▎ | 367603/445500 [00:43<00:09, 8468.62 examples/s]

Map:  83%|████████▎ | 368852/445500 [00:43<00:09, 8415.16 examples/s]

Map:  83%|████████▎ | 370037/445500 [00:44<00:09, 8249.57 examples/s]

Map:  83%|████████▎ | 370881/445500 [00:44<00:08, 8293.15 examples/s]

Map:  83%|████████▎ | 371721/445500 [00:44<00:08, 8313.68 examples/s]

Map:  84%|████████▎ | 372561/445500 [00:44<00:08, 8334.49 examples/s]

Map:  84%|████████▍ | 373422/445500 [00:44<00:08, 8408.32 examples/s]

Map:  84%|████████▍ | 374265/445500 [00:44<00:08, 8410.95 examples/s]

Map:  84%|████████▍ | 375515/445500 [00:44<00:08, 8377.11 examples/s]

Map:  85%|████████▍ | 376771/445500 [00:44<00:08, 8371.96 examples/s]

Map:  85%|████████▍ | 378030/445500 [00:44<00:08, 8375.78 examples/s]

Map:  85%|████████▌ | 378875/445500 [00:45<00:07, 8390.52 examples/s]

Map:  85%|████████▌ | 379746/445500 [00:45<00:07, 8471.59 examples/s]

Map:  86%|████████▌ | 381014/445500 [00:45<00:07, 8461.20 examples/s]

Map:  86%|████████▌ | 382243/445500 [00:45<00:07, 8364.88 examples/s]

Map:  86%|████████▌ | 383089/445500 [00:45<00:07, 8384.48 examples/s]

Map:  86%|████████▌ | 383945/445500 [00:45<00:07, 8426.78 examples/s]

Map:  86%|████████▋ | 385199/445500 [00:45<00:07, 8397.65 examples/s]

Map:  87%|████████▋ | 386462/445500 [00:45<00:07, 8400.51 examples/s]

Map:  87%|████████▋ | 387705/445500 [00:46<00:06, 8360.13 examples/s]

Map:  87%|████████▋ | 388545/445500 [00:46<00:06, 8361.03 examples/s]

Map:  87%|████████▋ | 389760/445500 [00:46<00:06, 8269.45 examples/s]

Map:  88%|████████▊ | 390606/445500 [00:46<00:06, 8314.94 examples/s]

Map:  88%|████████▊ | 391450/445500 [00:46<00:06, 8343.12 examples/s]

Map:  88%|████████▊ | 392712/445500 [00:46<00:06, 8365.96 examples/s]

Map:  88%|████████▊ | 393970/445500 [00:46<00:06, 8366.53 examples/s]

Map:  89%|████████▊ | 394817/445500 [00:46<00:06, 8386.66 examples/s]

Map:  89%|████████▉ | 396044/445500 [00:47<00:05, 8311.40 examples/s]

Map:  89%|████████▉ | 396921/445500 [00:47<00:05, 8419.45 examples/s]

Map:  89%|████████▉ | 397768/445500 [00:47<00:05, 8428.99 examples/s]

Map:  90%|████████▉ | 399009/445500 [00:47<00:05, 8371.46 examples/s]

Map:  90%|████████▉ | 400204/445500 [00:47<00:05, 8231.77 examples/s]

Map:  90%|█████████ | 401433/445500 [00:47<00:05, 8214.59 examples/s]

Map:  90%|█████████ | 402265/445500 [00:47<00:05, 8235.57 examples/s]

Map:  90%|█████████ | 403105/445500 [00:47<00:05, 8269.96 examples/s]

Map:  91%|█████████ | 403945/445500 [00:48<00:05, 8296.95 examples/s]

Map:  91%|█████████ | 405183/445500 [00:48<00:04, 8277.53 examples/s]

Map:  91%|█████████ | 406042/445500 [00:48<00:04, 8345.92 examples/s]

Map:  91%|█████████▏| 406902/445500 [00:48<00:04, 8405.66 examples/s]

Map:  92%|█████████▏| 408143/445500 [00:48<00:04, 8354.25 examples/s]

Map:  92%|█████████▏| 409000/445500 [00:48<00:04, 8397.98 examples/s]

Map:  92%|█████████▏| 409867/445500 [00:48<00:04, 8466.35 examples/s]

Map:  92%|█████████▏| 410731/445500 [00:48<00:04, 8510.72 examples/s]

Map:  92%|█████████▏| 411979/445500 [00:49<00:03, 8434.68 examples/s]

Map:  93%|█████████▎| 413211/445500 [00:49<00:03, 8352.97 examples/s]

Map:  93%|█████████▎| 414065/445500 [00:49<00:03, 8397.53 examples/s]

Map:  93%|█████████▎| 414950/445500 [00:49<00:03, 8511.48 examples/s]

Map:  93%|█████████▎| 416183/445500 [00:49<00:03, 8405.31 examples/s]

Map:  94%|█████████▎| 417433/445500 [00:49<00:03, 8376.14 examples/s]

Map:  94%|█████████▍| 418684/445500 [00:49<00:03, 8360.31 examples/s]

Map:  94%|█████████▍| 419529/445500 [00:49<00:03, 8379.82 examples/s]

Map:  94%|█████████▍| 420784/445500 [00:50<00:02, 8371.86 examples/s]

Map:  95%|█████████▍| 421628/445500 [00:50<00:02, 8387.57 examples/s]

Map:  95%|█████████▍| 422896/445500 [00:50<00:02, 8404.71 examples/s]

Map:  95%|█████████▌| 423748/445500 [00:50<00:02, 8429.98 examples/s]

Map:  95%|█████████▌| 424988/445500 [00:50<00:02, 8372.25 examples/s]

Map:  96%|█████████▌| 425827/445500 [00:50<00:02, 8373.97 examples/s]

Map:  96%|█████████▌| 426670/445500 [00:50<00:02, 8384.61 examples/s]

Map:  96%|█████████▌| 427938/445500 [00:50<00:02, 8406.95 examples/s]

Map:  96%|█████████▋| 429173/445500 [00:51<00:01, 8341.84 examples/s]

Map:  97%|█████████▋| 430016/445500 [00:51<00:01, 8361.04 examples/s]

Map:  97%|█████████▋| 430915/445500 [00:51<00:01, 8520.90 examples/s]

Map:  97%|█████████▋| 432176/445500 [00:51<00:01, 8476.76 examples/s]

Map:  97%|█████████▋| 433433/445500 [00:51<00:01, 8443.58 examples/s]

Map:  97%|█████████▋| 434280/445500 [00:51<00:01, 8448.91 examples/s]

Map:  98%|█████████▊| 435133/445500 [00:51<00:01, 8466.97 examples/s]

Map:  98%|█████████▊| 436408/445500 [00:51<00:01, 8476.02 examples/s]

Map:  98%|█████████▊| 437265/445500 [00:52<00:00, 8496.90 examples/s]

Map:  98%|█████████▊| 438129/445500 [00:52<00:00, 8532.63 examples/s]

Map:  99%|█████████▊| 439000/445500 [00:52<00:00, 8566.78 examples/s]

Map:  99%|█████████▊| 439888/445500 [00:52<00:00, 8651.11 examples/s]

Map:  99%|█████████▉| 441151/445500 [00:52<00:00, 8558.22 examples/s]

Map:  99%|█████████▉| 442419/445500 [00:52<00:00, 8468.64 examples/s]

Map: 100%|█████████▉| 443701/445500 [00:52<00:00, 8492.20 examples/s]

Map: 100%|█████████▉| 444963/445500 [00:52<00:00, 8455.90 examples/s]

Map: 100%|██████████| 445500/445500 [00:53<00:00, 8400.79 examples/s]

Map:   0%|          | 0/200 [00:00<?, ? examples/s]

Map: 100%|██████████| 200/200 [00:00<00:00, 4963.53 examples/s]

train examples: 445,500 | eval examples: 200

trainable params: 1,572,864 || all params: 566,036,480 || trainable%: 0.2779

/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/torch/utils/data/dataloader.py:684: UserWarning: 'pin_memory' argument is set as true but not supported on MPS now, then device pinned memory won't be used.
  warnings.warn(warn_msg)

saved adapter to models/genre_module_dgt (13.1 min)

{'module': 'genre',
 'baseline_loss': 7.896988391876221,
 'final_loss': 6.656613349914551,
 'minutes': 13.142190432548523}

## 5. Train the language module

`l` = Finnish, learned from OPUS Books (¬𝑔, the literary genre) — the small, ~64k-token corpus
flagged in the previous notebook.

In [ ]:
# l = Finnish, learned from OPUS Books (¬g, the literary genre) 
language_result = train_module(
    name="language",
    train_path=DATA_DIR / "language_module_books_fi" / "train.jsonl",
    dev_path=DATA_DIR / "language_module_books_fi" / "dev.jsonl",
    output_dir=MODELS_DIR / "language_module_books_fi",
)
language_result

=== training language module ===

Map:   0%|          | 0/4285 [00:00<?, ? examples/s]

Map:   1%|          | 47/4285 [00:00<00:09, 438.57 examples/s]

Map:  23%|██▎       | 1000/4285 [00:00<00:00, 5080.52 examples/s]

Map:  49%|████▊     | 2083/4285 [00:00<00:00, 7516.24 examples/s]

Map:  73%|███████▎  | 3145/4285 [00:00<00:00, 8685.07 examples/s]

Map:  98%|█████████▊| 4210/4285 [00:00<00:00, 9368.53 examples/s]

Map: 100%|██████████| 4285/4285 [00:00<00:00, 8006.22 examples/s]

Generating train split: 0 examples [00:00, ? examples/s]

Generating train split: 200 examples [00:00, 162601.43 examples/s]

Map:   0%|          | 0/200 [00:00<?, ? examples/s]

Map: 100%|██████████| 200/200 [00:00<00:00, 8451.32 examples/s]

train examples: 4,285 | eval examples: 200

trainable params: 1,572,864 || all params: 566,036,480 || trainable%: 0.2779

saved adapter to models/language_module_books_fi (10.1 min)

{'module': 'language',
 'baseline_loss': 5.626596450805664,
 'final_loss': 3.8033013343811035,
 'minutes': 10.104913079738617}

## 6. Summary

Both baseline numbers are the plain backbone's loss on that module's own dev set

In [7]:
import pandas as pd

summary = pd.DataFrame([genre_result, language_result])
# perplexity = exp(mean NLL); using e explicitly here since the loss is natural-log cross-entropy
summary["ppl_baseline"] = summary["baseline_loss"].apply(lambda x: round(pow(2.718281828, x), 2))
summary["ppl_final"] = summary["final_loss"].apply(lambda x: round(pow(2.718281828, x), 2))
summary

     module  baseline_loss  final_loss    minutes  ppl_baseline  ppl_final
0     genre       7.896988    6.656613  13.142190       2689.17     777.91
1  language       5.626596    3.803301  10.104913        277.72      44.85

In [8]:
# confirms only the small LoRA deltas were saved (a few MB), not full backbone copies
for d in [MODELS_DIR / "genre_module_dgt", MODELS_DIR / "language_module_books_fi"]:
    size_mb = sum(f.stat().st_size for f in d.glob("*.safetensors")) / 1e6
    print(f"{d}: {size_mb:.1f} MB (adapter weights only)")

models/genre_module_dgt: 6.3 MB (adapter weights only)
models/language_module_books_fi: 6.3 MB (adapter weights only)